package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household

import accessnyc.rules.income.IncomeHouseholdWageSelfEmploymentBoarderMonthly
import accessnyc.rules.snap.IncomeHouseholdAllSSIOrCash
import accessnyc.rules.snap.IncomeHouseholdMinusChildSupportPaid
import accessnyc.rules.expense.ExpenseHouseholdHasChildOrDependentCare
import accessnyc.rules.snap.IncomeSNAP

rule "s2_r007.2"
    dialect "mvel"
    
    when
        Household(city == "NYC")
        IncomeHouseholdAllSSIOrCash(value == true)  

    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("2")
        insertLogical($programcode)
end


rule "s2_r007 200% of poverty level gross income: child care, dependent care, elderly person, disability, or blind"
    dialect "mvel"
    when
        Household(city == "NYC")
        ( 
            ExpenseHouseholdHasChildOrDependentCare(value == true) or
            Person( age >= 60 ) or
            Person(disabled == true) or
            Person( blind == true)
        )
        (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 2265))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 3052))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 3838))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 4625))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 5412))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 6198))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 6985))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 7772))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end

rule "s2_r007 150% of poverty level gross income: has earned income"
    dialect "mvel"
    
    when
        Household(city == "NYC")
        IncomeHouseholdWageSelfEmploymentBoarderMonthly(amount > 0)
        (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 1699))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2289))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 2879))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 3469))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 4059))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 4649))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 5239))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 5829))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end

rule "s2_r007 130% of poverty level gross income: all other"
    dialect "mvel"
    
    when
        Household(city == "NYC")
       (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 1473))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 1984))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 2495))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 3007))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 3518))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 4029))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 4541))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 5052))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end