package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomePersonHasDM
import accessnyc.rules.income.IncomeHouseholdTotalYearly

rule "s2_047.1 and s2_047.2 and s2_047.3"
    dialect "mvel"
    
    when
        Household(city == "NYC")
        (
            (Person( blind == true ))
            or (Person( disabled == true ))
            or (Person( benefitsMedicaidDisability == true ))
        )
    then
        $programcode = new EligibleProgram()    
        $programcode.setCode("S2R047")
        insertLogical($programcode)  
end

rule "s2_r043.4 "
    dialect "mvel"
    
    when
        Household(city == "NYC")
        IncomePersonHasDM( value == true )
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R047")
        insertLogical($programcode)   
    
end