package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

rule "S2R027"
    dialect "mvel"
    
    when 
        Household(city == "NYC") 
        Person( age >= 60 )
        and (
               (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 18954))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 25636))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 32318))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 39000))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 45682))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 52364))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 59046))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 65728))
            )
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R027")
        insertLogical($programcode)

end