package accessnyc.rules;
import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeAdultsTotalMonthly
import accessnyc.rules.expense.ExpenseHouseholdHasHeating


rule "s2_r019"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        (Person( age <= 6) or Person( age >= 60) or Person( disabled == true ) or Person( blind == true ))
        (
            IncomeHouseholdHasCashAssistance( value == true )
            or (Household(members == 1) and IncomeHouseholdHasSSI( value == true ))
            or (Household(members == 1) and IncomeAdultsTotalMonthly(amount <= 3035))
            or (Household(members == 2) and IncomeAdultsTotalMonthly(amount <= 3970))
            or (Household(members == 3) and IncomeAdultsTotalMonthly(amount <= 4904))
            or (Household(members == 4) and IncomeAdultsTotalMonthly(amount <= 5838))
            or (Household(members == 5) and IncomeAdultsTotalMonthly(amount <= 6772))
            or (Household(members == 6) and IncomeAdultsTotalMonthly(amount <= 7706))
            or (Household(members == 7) and IncomeAdultsTotalMonthly(amount <= 7881))
            or (Household(members == 8) and IncomeAdultsTotalMonthly(amount <= 8056))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R019")
        insertLogical($programcode)

end