package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household

import accessnyc.rules.income.IncomeHouseholdMonthlyCAMinusWorkExpense

rule "s2_r010.2"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        (Person( age <= 18) or Person( pregnant == true ))
        (
               (Household(members == 1) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 460.1))
            or (Household(members == 2) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 574.5))
            or (Household(members == 3) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 789))
            or (Household(members == 4) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 951.7))
            or (Household(members == 5) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 1119.7))
            or (Household(members == 6) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 1238.2))
            or (Household(members == 7) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 1357.7))
            or (Household(members == 8) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 1455.2))
        )        

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R010")
        insertLogical($programcode)


end

rule "s2_r010.3"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        (
               (Household(members == 1) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 398.1))
            or (Household(members == 2) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 541.5))
            or (Household(members == 3) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 675))
            or (Household(members == 4) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 813.7))
            or (Household(members == 5) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 955.7))
            or (Household(members == 6) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 1063.2))
            or (Household(members == 7) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 1214.7))
            or (Household(members == 8) and IncomeHouseholdMonthlyCAMinusWorkExpense(amount < 1330.2))
        )
    

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R010")
        insertLogical($programcode)

end
