package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

rule "s2_r039"
    dialect "mvel"
    
    when 
        Household( city == "NYC" )
        (
            (Household( members == 1 ) and IncomeHouseholdTotalYearly ( amount <= 56000 ))
            or (Household( members > 1 ) and IncomeHouseholdTotalYearly ( amount <= 80000 ))
        )
       
    then

        $programcode = new EligibleProgram()
        $programcode.setCode("S2R039")
        insertLogical($programcode)

end