package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "S2R030"
    dialect "mvel"
    
    when 
        Household( city == "NYC")
        Person( age >= 14, age <= 24 )
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R030")
        insertLogical($programcode)

end
