package accessnyc.rules;
import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

// FairFares Rule
rule "s2_r034"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        Person( age >= 18, age <= 64)
        ( 
          (Household(members == 1) and IncomeHouseholdTotalYearly( amount <= 18072) ) or 
          (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 24528)) or
          (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 30984)) or 
          (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 37440)) or 
          (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 43896)) or 
          (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 50352)) or 
          (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 56808)) or
          (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 63264))
        
        ) 
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R034")
        insertLogical($programcode)

end