package accessnyc.rules;
import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeAdultsTotalMonthly
import accessnyc.rules.expense.ExpenseHouseholdHasHeating


rule "s2_r019"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        not (Household(livingRentalType == "NYCHA") and not (ExpenseHouseholdHasHeating(value == true))) // need to check this logic is working
        not Household(livingHotel == true)
        not Household(livingShelter == true)
        (
               (Household(members == 1) and IncomeAdultsTotalMonthly(amount <= 2729))
            or (Household(members == 2) and IncomeAdultsTotalMonthly(amount <= 3569))
            or (Household(members == 3) and IncomeAdultsTotalMonthly(amount <= 4409))
            or (Household(members == 4) and IncomeAdultsTotalMonthly(amount <= 5249))
            or (Household(members == 5) and IncomeAdultsTotalMonthly(amount <= 6088))
            or (Household(members == 6) and IncomeAdultsTotalMonthly(amount <= 6928))
            or (Household(members == 7) and IncomeAdultsTotalMonthly(amount <= 7086))
            or (Household(members == 8) and IncomeAdultsTotalMonthly(amount <= 7243))
            or (Household(members == 9) and IncomeAdultsTotalMonthly(amount <= 7401))
            or (Household(members == 10) and IncomeAdultsTotalMonthly(amount <= 7558))
            or (Household(members == 11) and IncomeAdultsTotalMonthly(amount <= 7715))
            or (Household(members == 12) and IncomeAdultsTotalMonthly(amount <= 7873))
            or (Household(members == 13) and IncomeAdultsTotalMonthly(amount <= 8420))
            )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R019")
        insertLogical($programcode)

end