package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdHasBenefit
import accessnyc.rules.income.IncomeHouseholdTotalYearly

rule "s2_r043.1"
    dialect "mvel"
    
    when
        Household(city == "NYC")
        (
            (Person( benefitsMedicaid == true ))
            or (Person( benefitsMedicaidDisability == true ))
        )
    then
        $programcode = new EligibleProgram()    
        $programcode.setCode("S2R043")
        insertLogical($programcode)  
end

rule "s2_r043.2"
    dialect "mvel"
    
    when
        Household(city == "NYC")
        IncomeHouseholdHasBenefit( value == true )
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R043")
        insertLogical($programcode)   
    
end

rule "s2_r043.3 "
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly( amount <= 19683 )) 
            or (Household(members == 2) and IncomeHouseholdTotalYearly( amount <= 26622 )) 
            or (Household(members == 3) and IncomeHouseholdTotalYearly( amount <= 33561 ))
            or (Household(members == 4) and IncomeHouseholdTotalYearly( amount <= 40500 ))
            or (Household(members == 5) and IncomeHouseholdTotalYearly( amount <= 47439 ))
            or (Household(members == 6) and IncomeHouseholdTotalYearly( amount <= 54378 ))
            or (Household(members == 7) and IncomeHouseholdTotalYearly( amount <= 61317 ))
            or (Household(members == 8) and IncomeHouseholdTotalYearly( amount <= 68256 ))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R043")
        insertLogical($programcode)

end