package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly


rule "s2_r013 "
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        Person(headOfHousehold == true, age >= 18)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly( amount <= 36550 )) 
            or (Household(members == 2) and IncomeHouseholdTotalYearly( amount <= 41750 )) 
            or (Household(members == 3) and IncomeHouseholdTotalYearly( amount <= 46950 ))
            or (Household(members == 4) and IncomeHouseholdTotalYearly( amount <= 52150 ))
            or (Household(members == 5) and IncomeHouseholdTotalYearly( amount <= 56350 ))
            or (Household(members == 6) and IncomeHouseholdTotalYearly( amount <= 60500 ))
            or (Household(members == 7) and IncomeHouseholdTotalYearly( amount <= 64700 ))
            or (Household(members == 8) and IncomeHouseholdTotalYearly( amount <= 68850 ))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R013")
        insertLogical($programcode)

end
