package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdHasBenefit
import accessnyc.rules.income.IncomeHouseholdTotalYearly

rule "s2_r043.1"
    dialect "mvel"
    
    when
        (
            (Person( benefitsMedicaid == true ))
            or (Person( benefitsMedicaidDisability == true ))
        )
    then
        $programcode = new EligibleProgram()    
        $programcode.setCode("S2R043")
        insertLogical($programcode)  
end

rule "s2_r043.2"
    dialect "mvel"
    
    when
        IncomeHouseholdHasBenefit( value == true )
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R043")
        insertLogical($programcode)   
    
end

rule "s2_r043.3"
    dialect "mvel"
    
    when
        Household( livingRenting == true, livingRentalType == "NYCHA")
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R043")
        insertLogical($programcode)   
    
end

rule "s2_r043.4"
    dialect "mvel"
    
    when 
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly( amount <= 20331 )) 
            or (Household(members == 2) and IncomeHouseholdTotalYearly( amount <= 27594 )) 
            or (Household(members == 3) and IncomeHouseholdTotalYearly( amount <= 34857 ))
            or (Household(members == 4) and IncomeHouseholdTotalYearly( amount <= 42120 ))
            or (Household(members == 5) and IncomeHouseholdTotalYearly( amount <= 49383 ))
            or (Household(members == 6) and IncomeHouseholdTotalYearly( amount <= 56646 ))
            or (Household(members == 7) and IncomeHouseholdTotalYearly( amount <= 63909 ))
            or (Household(members == 8) and IncomeHouseholdTotalYearly( amount <= 71172 ))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R043")
        insertLogical($programcode)

end