package accessnyc.rules;

import accessnyc.request.Household
import accessnyc.request.Person
import accessnyc.rules.income.IncomeHouseholdHasBenefit
import accessnyc.rules.income.IncomeHouseholdTotalYearly

rule "S2R053 ACP 1-4"
    dialect "mvel"
    
    when
        Household( city == "NYC" )
        (
            Person( benefitsMedicaid == true ) // rule 2
            or Person( benefitsMedicaidDisability == true ) // rule 2
            or IncomeHouseholdHasBenefit(value == true) // rule 3
            or Person( age <= 21, studentFulltime == true ) // rule 4
        )
        
    then
        
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R053")
        insertLogical($programcode)

end

rule "S2R053 ACP income by # of household members"
    dialect "mvel"
    
    when
        Household( city == "NYC" )
        ( 
          (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 29160) ) or 
          (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 39440)) or
          (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 49720)) or 
          (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 60000)) or 
          (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 70280)) or 
          (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 80560)) or 
          (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 90840)) or
          (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 101120))
        ) 
        
    then
        
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R053")
        insertLogical($programcode)

end