package accessnyc.rules;
import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeAdultsTotalMonthly
import accessnyc.rules.expense.ExpenseHouseholdHasHeating


rule "s2_r033"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        (Person( age <= 6) or Person( age >= 60) or Person( disabled == true ) or Person( blind == true ))
        (
            IncomeHouseholdHasCashAssistance( value == true )
            or (Household(members == 1) and IncomeHouseholdHasSSI( value == true ))
            or (Household(members == 1) and IncomeHouseholdTotalMonthly(amount <= 2852))
            or (Household(members == 2) and IncomeHouseholdTotalMonthly(amount <= 3730))
            or (Household(members == 3) and IncomeHouseholdTotalMonthly(amount <= 4608))
            or (Household(members == 4) and IncomeHouseholdTotalMonthly(amount <= 5485))
            or (Household(members == 5) and IncomeHouseholdTotalMonthly(amount <= 6363))
            or (Household(members == 6) and IncomeHouseholdTotalMonthly(amount <= 7241))
            or (Household(members == 7) and IncomeHouseholdTotalMonthly(amount <= 7405))
            or (Household(members == 8) and IncomeHouseholdTotalMonthly(amount <= 7570))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R033")
        insertLogical($programcode)

end