package accessnyc.rules;
import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

// Public Housing Rule
rule "s2_r035"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        Person( age >= 18, headOfHousehold==true)
        not (
            Person( age < 18, headOfHouseholdRelation=="Spouse") or
            Person( age < 18, headOfHouseholdRelation=="DomesticPartner")
        )
        (
            Household(members==1) or
            Person(headOfHouseholdRelation=="Spouse") or
            Person(headOfHouseholdRelation=="Child") or
            Person(headOfHouseholdRelation=="FosterChild") or
            Person(headOfHouseholdRelation=="Parent") or
            Person(headOfHouseholdRelation=="Grandparent") or
            Person(headOfHouseholdRelation=="FosterParent") or
            Person(headOfHouseholdRelation=="SisterBrother") or
            Person(headOfHouseholdRelation=="DomesticPartner") or
            Person(headOfHouseholdRelation=="StepChild") or
            Person(headOfHouseholdRelation=="StepParent") or
            Person(headOfHouseholdRelation=="StepSisterStepBrother")
        )
        ( 
          (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 66850)) or 
          (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 76400)) or
          (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 84950)) or 
          (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 95450)) or 
          (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 103100)) or 
          (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 110750)) or 
          (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 118400)) or
          (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 126000))
        ) 
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R035")
        insertLogical($programcode)

end