package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household

import accessnyc.rules.income.IncomeHouseholdWageSelfEmploymentBoarderMonthly
import accessnyc.rules.snap.IncomeHouseholdAllSSIOrCash
import accessnyc.rules.snap.IncomeHouseholdMinusChildSupportPaid
import accessnyc.rules.expense.ExpenseHouseholdHasChildOrDependentCare
import accessnyc.rules.snap.IncomeSNAP

rule "s2_r007.2"
    dialect "mvel"
    
    when
        Household(city == "NYC")
        IncomeHouseholdAllSSIOrCash(value == true)  

    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("2")
        insertLogical($programcode)
end


rule "s2_r007 200% of poverty level gross income: child care, dependent care, elderly person, disability, or blind"
    dialect "mvel"
    when
        Household(city == "NYC")
        ( 
            ExpenseHouseholdHasChildOrDependentCare(value == true) or
            Person( age >= 60 ) or
            Person(disabled == true) or
            Person( blind == true)
        )
        (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 2430))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 3287))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 4143))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 5000))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 5857))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 6713))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 7570))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 8427))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end

rule "s2_r007 150% of poverty level gross income: has earned income"
    dialect "mvel"
    
    when
        Household(city == "NYC")
        IncomeHouseholdWageSelfEmploymentBoarderMonthly(amount > 0)
        (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 1823))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2465))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 3108))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 3750))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 4393))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 5035))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 5678))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 6320))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end

rule "s2_r007 130% of poverty level gross income: all other"
    dialect "mvel"
    
    when
        Household(city == "NYC")
       (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 1580))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2137))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 2694))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 3250))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 3807))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 4364))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 4921))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 5478))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end