package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalMonthly
import accessnyc.rules.household.MembersPlusPregnant

rule "S2R029"
    dialect "mvel"
    
    when 
        Household( city == "NYC")
        Person( pregnant == true )
        and (
               (MembersPlusPregnant(value == 2) and IncomeHouseholdTotalMonthly(amount <= 2960))
            or (MembersPlusPregnant(value == 3) and IncomeHouseholdTotalMonthly(amount <= 3733))
            or (MembersPlusPregnant(value == 4) and IncomeHouseholdTotalMonthly(amount <= 4606))
            or (MembersPlusPregnant(value == 5) and IncomeHouseholdTotalMonthly(amount <= 5280))
            or (MembersPlusPregnant(value == 6) and IncomeHouseholdTotalMonthly(amount <= 6053))
            or (MembersPlusPregnant(value == 7) and IncomeHouseholdTotalMonthly(amount <= 6826))
            or (MembersPlusPregnant(value == 8) and IncomeHouseholdTotalMonthly(amount <= 7599))
            )
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R029")
        insertLogical($programcode)


end