package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "s2_r037"
    dialect "mvel"
    
    when 

        Household( city == "NYC")
        Person( benefitsMedicaid == true) 
       
    then

        $programcode = new EligibleProgram()
        $programcode.setCode("S2R037")
        insertLogical($programcode)

end
