package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.household.MembersPlusPregnantMinusFoster
import accessnyc.rules.income.IncomeHouseholdTotalMonthlyLessFoster
import accessnyc.rules.income.IncomePersonMonthly


rule "s2_r022.1a1"
    dialect "mvel"
    
    when 
        IncomePersonMonthly(person.headOfHouseholdRelation == "FosterChild", person.pregnant == true, amount <= 2538)
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R022")
        insertLogical($programcode)

end

rule "s2_r022.1a2"
    dialect "mvel"
    
    when 
        IncomePersonMonthly(person.headOfHouseholdRelation == "FosterChild", person.pregnant == false, person.age < 5, amount <= 1872)
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R022")
        insertLogical($programcode)

end


rule "s2_r022.2"
    dialect "mvel"
    
    when 
        Person(headOfHouseholdRelation not in ("FosterChild"), pregnant == true)
        and (
            (MembersPlusPregnantMinusFoster(value == 1) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 1872))
            or (MembersPlusPregnantMinusFoster(value == 2) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 2538))
            or (MembersPlusPregnantMinusFoster(value == 3) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 3204))
            or (MembersPlusPregnantMinusFoster(value == 4) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 3870))
            or (MembersPlusPregnantMinusFoster(value == 5) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 4536))
            or (MembersPlusPregnantMinusFoster(value == 6) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 5202))
            or (MembersPlusPregnantMinusFoster(value == 7) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 5868))
            or (MembersPlusPregnantMinusFoster(value == 8) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 6534))
            )
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R022")
        insertLogical($programcode)

end

rule "s2_r022.3"
    dialect "mvel"
    
    when 
        Person(headOfHouseholdRelation not in ("FosterChild"), pregnant == false, age < 5 )
        and (
            (MembersPlusPregnantMinusFoster(value == 1) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 1872))
            or (MembersPlusPregnantMinusFoster(value == 2) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 2538))
            or (MembersPlusPregnantMinusFoster(value == 3) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 3204))
            or (MembersPlusPregnantMinusFoster(value == 4) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 3870))
            or (MembersPlusPregnantMinusFoster(value == 5) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 4536))
            or (MembersPlusPregnantMinusFoster(value == 6) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 5202))
            or (MembersPlusPregnantMinusFoster(value == 7) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 5868))
            or (MembersPlusPregnantMinusFoster(value == 8) and IncomeHouseholdTotalMonthlyLessFoster(amount <= 6534))
            )
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R022")
        insertLogical($programcode)

end