package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly
import accessnyc.rules.income.IncomeHouseholdHasUI


rule "s2_r041.2 - one or more household member has an Unemployment Insurance income"
 dialect "mvel"
    
    when 
        Household(city == "NYC")
        IncomeHouseholdHasUI( value == true )
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R041")
        insertLogical($programcode)   
end

rule "s2_r041.3 "
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        Person(headOfHousehold == true, age >= 18)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly( amount <= 66850 )) 
            or (Household(members == 2) and IncomeHouseholdTotalYearly( amount <= 76400 )) 
            or (Household(members == 3) and IncomeHouseholdTotalYearly( amount <= 85950 ))
            or (Household(members == 4) and IncomeHouseholdTotalYearly( amount <= 95450 ))
            or (Household(members == 5) and IncomeHouseholdTotalYearly( amount <= 103100 ))
            or (Household(members == 6) and IncomeHouseholdTotalYearly( amount <= 110750 ))
            or (Household(members == 7) and IncomeHouseholdTotalYearly( amount <= 118400 ))
            or (Household(members == 8) and IncomeHouseholdTotalYearly( amount <= 126000 ))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R041")
        insertLogical($programcode)

end