package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


import accessnyc.rules.snap.IncomeHouseholdAllSSIOrCash
import accessnyc.rules.snap.IncomeHouseholdMinusChildSupportPaid
import accessnyc.rules.expense.ExpenseHouseholdHasDependentCare
import accessnyc.rules.snap.IncomeSNAP

rule "s2_r007.2"
    dialect "mvel"
    
    when
        
        Household(city == "NYC")
        IncomeHouseholdAllSSIOrCash(value == true)  

    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("2")
        insertLogical($programcode)
end


rule "s2_r007.3 blind"
    dialect "mvel"
    when
        Household(city == "NYC")
        Person( blind == true) 
        (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 2126))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2873))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 3620))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 4366))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 5113))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 5860))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 6606))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 7353))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("3")
        insertLogical($programcode)
end


rule "s2_r007.3 blind snap income"
    dialect "mvel"
    when
        Household(city == "NYC")
        Person( blind == true) 
        (
               (Household(members == 1, cashOnHand <= 3500) and IncomeSNAP(amount <= 1064))
            or (Household(members == 2, cashOnHand <= 3500) and IncomeSNAP(amount <= 1437))
            or (Household(members == 3, cashOnHand <= 3500) and IncomeSNAP(amount <= 1810))
            or (Household(members == 4, cashOnHand <= 3500) and IncomeSNAP(amount <= 2184))
            or (Household(members == 5, cashOnHand <= 3500) and IncomeSNAP(amount <= 2557))
            or (Household(members == 6, cashOnHand <= 3500) and IncomeSNAP(amount <= 2930))
            or (Household(members == 7, cashOnHand <= 3500) and IncomeSNAP(amount <= 3304))
            or (Household(members == 8, cashOnHand <= 3500) and IncomeSNAP(amount <= 3677))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("3")
        insertLogical($programcode)
end

rule "s2_r007.3b"
    dialect "mvel"
    when
        Household(city == "NYC")
        Person(disabled == true) 
        (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 2126))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2873))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 3620))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 4366))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 5113))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 5860))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 6606))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 7353))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("3")
        insertLogical($programcode)
end

rule "s2_r007.3b snap budget"
    dialect "mvel"
    when
        Household(city == "NYC")
        Person(disabled == true) 
        (
               (Household(members == 1, cashOnHand <= 3500) and IncomeSNAP(amount <= 1064))
            or (Household(members == 2, cashOnHand <= 3500) and IncomeSNAP(amount <= 1437))
            or (Household(members == 3, cashOnHand <= 3500) and IncomeSNAP(amount <= 1810))
            or (Household(members == 4, cashOnHand <= 3500) and IncomeSNAP(amount <= 2184))
            or (Household(members == 5, cashOnHand <= 3500) and IncomeSNAP(amount <= 2557))
            or (Household(members == 6, cashOnHand <= 3500) and IncomeSNAP(amount <= 2930))
            or (Household(members == 7, cashOnHand <= 3500) and IncomeSNAP(amount <= 3304))
            or (Household(members == 8, cashOnHand <= 3500) and IncomeSNAP(amount <= 3677))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("3")
        insertLogical($programcode)
end

rule "s2_r007.3c"
    dialect "mvel"
    when
        Household(city == "NYC")
        Person( age >= 60 )
        (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 2126))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2873))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 3620))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 4366))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 5113))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 5860))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 6606))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 7353))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("3")
        insertLogical($programcode)
end

rule "s2_r007.3c snap budget"
    dialect "mvel"
    when
        Household(city == "NYC")
        Person( age >= 60 )
        (
               (Household(members == 1, cashOnHand <= 3500) and IncomeSNAP(amount <= 1064))
            or (Household(members == 2, cashOnHand <= 3500) and IncomeSNAP(amount <= 1473))
            or (Household(members == 3, cashOnHand <= 3500) and IncomeSNAP(amount <= 1810))
            or (Household(members == 4, cashOnHand <= 3500) and IncomeSNAP(amount <= 2184))
            or (Household(members == 5, cashOnHand <= 3500) and IncomeSNAP(amount <= 2557))
            or (Household(members == 6, cashOnHand <= 3500) and IncomeSNAP(amount <= 2930))
            or (Household(members == 7, cashOnHand <= 3500) and IncomeSNAP(amount <= 3304))
            or (Household(members == 8, cashOnHand <= 3500) and IncomeSNAP(amount <= 3677))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("3")
        insertLogical($programcode)
end


rule "s2_r007.4"
    dialect "mvel"
    
    when
        
        Household(city == "NYC")
        ExpenseHouseholdHasDependentCare(value == true)
       (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 2126))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2873))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 3620))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 4366))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 5113))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 5860))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 6606))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 7353))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("4")
        insertLogical($programcode)
end

rule "s2_r007.5"
    dialect "mvel"
    
    when
        
        Household(city == "NYC")
       (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 1595))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2155))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 2715))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 3275))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 3835))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 4395))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 4955))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 5515))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("5")
        insertLogical($programcode)
end