package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

rule "s2_044.2 "
    dialect "mvel"

    when
        Household(city == "NYC")
        Person(unemployed == true, unemployedWorkedLast18Months == true)
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R044")
        insertLogical($programcode) 
end

rule "s2_r044.3 "
    dialect "mvel"
    
    when
        (
            (Person( benefitsMedicaid == true ))
            or (Person( benefitsMedicaidDisability == true ))
        )
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R044")
        insertLogical($programcode)   
    
end

rule "s2_r044.4 "
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        Person(headOfHousehold == true, age >= 18)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly( amount <= 17388 )) 
            or (Household(members == 2) and IncomeHouseholdTotalYearly( amount <= 23517 )) 
            or (Household(members == 3) and IncomeHouseholdTotalYearly( amount <= 29646 ))
            or (Household(members == 4) and IncomeHouseholdTotalYearly( amount <= 35775 ))
            or (Household(members == 5) and IncomeHouseholdTotalYearly( amount <= 41904 ))
            or (Household(members == 6) and IncomeHouseholdTotalYearly( amount <= 48033 ))
            or (Household(members == 7) and IncomeHouseholdTotalYearly( amount <= 54162 ))
            or (Household(members == 8) and IncomeHouseholdTotalYearly( amount <= 60291 ))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R044")
        insertLogical($programcode)

end