package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

rule "s2_r025"
    dialect "mvel"
    
    when 
        Household( city == "NYC" )
        Person( age >= 55, unemployed == true )
        
        (
               (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 18225))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 24650))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 31075))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 37500))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 43925))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 50350))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 56775))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 63200))
        )
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R025")
        insertLogical($programcode)

end


