package accessnyc.rules.expense;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExpenseHouseholdMedicalMonthly implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Float amount;

   public ExpenseHouseholdMedicalMonthly()
   {
   }

   public java.lang.Float getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Float amount)
   {
      this.amount = amount;
   }

   public ExpenseHouseholdMedicalMonthly(java.lang.Float amount)
   {
      this.amount = amount;
   }

}