package accessnyc.request;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Expense implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Float amount;
   private java.lang.String frequency;
   private java.lang.String type;

   public Expense()
   {
   }

   public java.lang.Float getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Float amount)
   {
      this.amount = amount;
   }

   public java.lang.String getFrequency()
   {
      return this.frequency;
   }

   public void setFrequency(java.lang.String frequency)
   {
      this.frequency = frequency;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public Expense(java.lang.Float amount, java.lang.String frequency,
         java.lang.String type)
   {
      this.amount = amount;
      this.frequency = frequency;
      this.type = type;
   }

}