package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "s2_r021 free lunch"
    dialect "mvel"
    
    when 
        Person(unemployed == true, unemployedWorkedLast18Months == true)

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R021")
        insertLogical($programcode)

end
