package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "s2_r057 age under 1"
    dialect "mvel"
    
    when 
        Person(age < 1)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly(amount > 33584))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount > 45582))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount > 57579))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount > 69576))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount > 81574))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount > 93571))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount > 105569))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount > 117566))
            )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R057")
        insertLogical($programcode)

end

rule "s2_r057 age 1-18"
    dialect "mvel"
    
    when 
        Person(age >= 1, age <= 18)
        not Person(age < 1)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly(amount > 23193))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount > 31478))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount > 39763))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount > 48048))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount > 56334))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount > 64619))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount > 72904))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount > 81189))
            )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R057")
        insertLogical($programcode)

end
