package accessnyc.rules;

import accessnyc.response.EligibleProgram
import accessnyc.rules.income.IncomeChildCareVoucherTotalMonthly
import accessnyc.rules.income.IncomePersonMonthly 
import accessnyc.request.Household
import accessnyc.request.Person
import accessnyc.rules.household.ChildCareVoucherHouseholdMembers

rule "s2_r040"
    dialect "mvel"

    when 
    // One of the following must be true:
	// - One of the children must be 12 or under
	// - Or, there must be a household member who is blind or disabled who is 19 or under
        (
            Person( age <= 13 ) or
            Person( age <= 19, disabled == true ) or
            Person( age <= 19, blind == true )
        )

          
    //And the household income among all of these members must fall in this range, or someone in the household must receive Cash Assistance     
        ( 
          (ChildCareVoucherHouseholdMembers(value == 2)  and IncomeChildCareVoucherTotalMonthly(amount <= 6435)) or
          (ChildCareVoucherHouseholdMembers(value == 3)  and IncomeChildCareVoucherTotalMonthly(amount <= 7949.74)) or 
          (ChildCareVoucherHouseholdMembers(value == 4)  and IncomeChildCareVoucherTotalMonthly(amount <= 9463.97)) or 
          (ChildCareVoucherHouseholdMembers(value == 5)  and IncomeChildCareVoucherTotalMonthly(amount <= 10978.20)) or 
          (ChildCareVoucherHouseholdMembers(value == 6)  and IncomeChildCareVoucherTotalMonthly(amount <= 12492.44)) or 
          (ChildCareVoucherHouseholdMembers(value == 7)  and IncomeChildCareVoucherTotalMonthly(amount <= 12776.36)) or
          (ChildCareVoucherHouseholdMembers(value == 8)  and IncomeChildCareVoucherTotalMonthly(amount <= 13060.28)) or
          IncomeHouseholdHasCashAssistance(value == true)
        ) 
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R040")
        insertLogical($programcode)

end
