package accessnyc.rules;
import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeAdultsTotalMonthly
import accessnyc.rules.expense.ExpenseHouseholdHasHeating


rule "s2_r019"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        not (Household(livingRentalType == "NYCHA") and not (ExpenseHouseholdHasHeating(value == true))) // need to check this logic is working
        not Household(livingHotel == true)
        (
               (Household(members == 1) and IncomeAdultsTotalMonthly(amount <= 2300))
            or (Household(members == 2) and IncomeAdultsTotalMonthly(amount <= 3007))
            or (Household(members == 3) and IncomeAdultsTotalMonthly(amount <= 3715))
            or (Household(members == 4) and IncomeAdultsTotalMonthly(amount <= 4423))
            or (Household(members == 5) and IncomeAdultsTotalMonthly(amount <= 5130))
            or (Household(members == 6) and IncomeAdultsTotalMonthly(amount <= 5838))
            or (Household(members == 7) and IncomeAdultsTotalMonthly(amount <= 5971))
            or (Household(members == 8) and IncomeAdultsTotalMonthly(amount <= 6103))
            
            
            )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R019")
        insertLogical($programcode)
        System.out.println("Rule s2_r019")

end