package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household

import accessnyc.rules.income.IncomeHouseholdWageSelfEmploymentBoarderMonthly
import accessnyc.rules.snap.IncomeHouseholdAllSSIOrCash
import accessnyc.rules.snap.IncomeHouseholdMinusChildSupportPaid
import accessnyc.rules.expense.ExpenseHouseholdHasChildOrDependentCare
import accessnyc.rules.snap.IncomeSNAP

rule "s2_r007.2"
    dialect "mvel"
    
    when
        Household(city == "NYC")
        IncomeHouseholdAllSSIOrCash(value == true)  

    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("2")
        insertLogical($programcode)
end


rule "s2_r007 200% of poverty level gross income: child care, dependent care, elderly person, disability, or blind"
    dialect "mvel"
    when
        Household(city == "NYC")
        ( 
            ExpenseHouseholdHasChildOrDependentCare(value == true) or
            Person( age >= 60 ) or
            Person(disabled == true) or
            Person( blind == true)
        )
        (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 2510))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 3407))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 4303))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 5200))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 6097))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 6993))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 7890))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 8787))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end

rule "s2_r007 150% of poverty level gross income: has earned income"
    dialect "mvel"
    
    when
        Household(city == "NYC")
        IncomeHouseholdWageSelfEmploymentBoarderMonthly(amount > 0)
        (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 1883))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2555))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 3228))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 3900))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 4573))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 5245))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 5918))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 6590))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end

rule "s2_r007 130% of poverty level gross income: all other"
    dialect "mvel"
    
    when
        Household(city == "NYC")
       (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 1632))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2215))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 2798))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 3380))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 3963))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 4546))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 5129))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 5712))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end