package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "s2_r009"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        Person( age >= 5, age <= 21, student == true)

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R009")
        insertLogical($programcode)

end