package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household

import accessnyc.rules.income.IncomeHouseholdWageSelfEmploymentBoarderMonthly
import accessnyc.rules.snap.IncomeHouseholdAllSSIOrCash
import accessnyc.rules.snap.IncomeHouseholdMinusChildSupportPaid
import accessnyc.rules.expense.ExpenseHouseholdHasChildOrDependentCare
import accessnyc.rules.snap.IncomeSNAP

rule "s2_r007.2"
    dialect "mvel"
    
    when
        IncomeHouseholdAllSSIOrCash(value == true)  

    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        $programcode.setRulePart("2")
        insertLogical($programcode)
end


rule "s2_r007 200% of poverty level gross income: child care, dependent care, elderly person, disability, or blind"
    dialect "mvel"
    when
        ( 
            ExpenseHouseholdHasChildOrDependentCare(value == true) or
            Person( age >= 60 ) or
            Person(disabled == true) or
            Person( blind == true)
        )
        (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 2660))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 3607))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 4553))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 5500))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 6447))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 7393))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 8340))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 9287))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end

rule "s2_r007 150% of poverty level gross income: has earned income"
    dialect "mvel"
    
    when
        IncomeHouseholdWageSelfEmploymentBoarderMonthly(amount > 0)
        (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 1995))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2705))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 3415))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 4125))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 4835))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 5545))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 6225))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 6965))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end

rule "s2_r007 130% of poverty level gross income: all other"
    dialect "mvel"
    
    when
       (
               (Household(members == 1) and IncomeHouseholdMinusChildSupportPaid(amount <= 1729))
            or (Household(members == 2) and IncomeHouseholdMinusChildSupportPaid(amount <= 2345))
            or (Household(members == 3) and IncomeHouseholdMinusChildSupportPaid(amount <= 2960))
            or (Household(members == 4) and IncomeHouseholdMinusChildSupportPaid(amount <= 3575))
            or (Household(members == 5) and IncomeHouseholdMinusChildSupportPaid(amount <= 4191))
            or (Household(members == 6) and IncomeHouseholdMinusChildSupportPaid(amount <= 4806))
            or (Household(members == 7) and IncomeHouseholdMinusChildSupportPaid(amount <= 5421))
            or (Household(members == 8) and IncomeHouseholdMinusChildSupportPaid(amount <= 6037))
        )
            
    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R007")
        insertLogical($programcode)
end