package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly
import accessnyc.rules.household.MembersPlusPregnant

rule "S2R029 pregnant, medicaid or disability medicaid"
    dialect "mvel"
    
    when 
        (Person( pregnant == true ))
        (Person(benefitsMedicaid == true) or Person(benefitsMedicaidDisability == true))
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R029")
        insertLogical($programcode)


end

rule "S2R029 income limits with pregnant household member"
    dialect "mvel"
    
    when 
        (Person( pregnant == true ))
        and (
               (MembersPlusPregnant(value == 1) and IncomeHouseholdTotalYearly(amount <= 34900))
            or (MembersPlusPregnant(value == 2) and IncomeHouseholdTotalYearly(amount <= 47165))
            or (MembersPlusPregnant(value == 3) and IncomeHouseholdTotalYearly(amount <= 59430))
            or (MembersPlusPregnant(value == 4) and IncomeHouseholdTotalYearly(amount <= 71695))
            or (MembersPlusPregnant(value == 5) and IncomeHouseholdTotalYearly(amount <= 83960))
            or (MembersPlusPregnant(value == 6) and IncomeHouseholdTotalYearly(amount <= 96225))
            or (MembersPlusPregnant(value == 7) and IncomeHouseholdTotalYearly(amount <= 108490))
            or (MembersPlusPregnant(value == 8) and IncomeHouseholdTotalYearly(amount <= 120755))
            or (MembersPlusPregnant(value == 9) and IncomeHouseholdTotalYearly(amount <= 133020))
            )
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R029")
        insertLogical($programcode)


end