package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "s2_r058"
    dialect "mvel"
    
    when 
        Person(age >= 19, age <= 64, benefitsMedicaid == false, benefitsMedicaidDisability == false)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly(amount > 22025, amount <= 39900))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount > 29864, amount <= 54100))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount > 37702, amount <= 68300))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount > 45540, amount <= 82500))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount > 53379, amount <= 96700))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount > 61217, amount <= 110900))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount > 69056, amount <= 125100))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount > 76894, amount <= 139300))
            )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R058")
        insertLogical($programcode)

end
