package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomePersonSESMonthly
import accessnyc.rules.income.IncomeHeadAndSpouseSESMonthly
import accessnyc.rules.household.HeadOfHouseholdMarried

rule "S2R025.4a"
    dialect "mvel"
    
    when 
        Household( city == "NYC")
        IncomePersonSESMonthly(person.age >= 55, person.unemployed == true, person.disabled == true, amount <= 1238)
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R025")
        $programcode.setRulePart("4a")
        insertLogical($programcode)
        System.out.println("Rule S2R025")

end

rule "S2R025.4b"
    dialect "mvel"
    
    when 
        Household( city == "NYC")
        IncomePersonSESMonthly(person.age >= 55, person.unemployed == true, person.headOfHousehold == false, person.headOfHouseholdRelation not in ("Spouse"), amount <= 1238)
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R025")
        $programcode.setRulePart("4b")
        insertLogical($programcode)
        System.out.println("Rule S2R025")

end


rule "S2R025.5a head of household married"
    dialect "mvel"
    
    when 
        Household( city == "NYC")
        Person( age >= 55, unemployed == true, disabled == false, headOfHousehold == true) 
        HeadOfHouseholdMarried(value == true)
        IncomeHeadAndSpouseSESMonthly(amount <= 1669)
        
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R025")
        $programcode.setRulePart("5a")
        insertLogical($programcode)
        System.out.println("Rule S2R025")

end

rule "S2R025.5a head of household unmarried"
    dialect "mvel"
    
    when 
        Household( city == "NYC")
        Person( age >= 55, unemployed == true, disabled == false, headOfHousehold == true) 
        not HeadOfHouseholdMarried( value == true)
        IncomeHeadAndSpouseSESMonthly(amount <= 1238)

        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R025")
        $programcode.setRulePart("5a")
        insertLogical($programcode)
        System.out.println("Rule S2R025")

end

rule "S2R025.5b spouse married"
    dialect "mvel"
    
    when 
        Household( city == "NYC")
        Person( age >= 55, unemployed == true, disabled == false, headOfHouseholdRelation == "Spouse") 
        HeadOfHouseholdMarried(value == true) 
        IncomeHeadAndSpouseSESMonthly(amount <= 1669)
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R025")
        $programcode.setRulePart("5b")
        insertLogical($programcode)
        System.out.println("Rule S2R025")

end

rule "S2R025.5b spouse unmarried"
    dialect "mvel"
    
    when 
        Household( city == "NYC")
        Person( age >= 55, unemployed == true, disabled == false, headOfHouseholdRelation == "Spouse") 
        not HeadOfHouseholdMarried( value == true) 
        IncomeHeadAndSpouseSESMonthly(amount <= 1238)

        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R025")
        $programcode.setRulePart("5b")
        insertLogical($programcode)
        System.out.println("Rule S2R025")

end

