package accessnyc.rules;
import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

// FairFares Rule
rule "s2_r034"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        Person( age >= 18, age <= 64)
        ( 
          (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 23475)) or 
          (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 31725)) or
          (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 39975)) or 
          (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 48225)) or 
          (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 56475)) or 
          (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 64725)) or 
          (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 72975)) or
          (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 81225))
        
        ) 
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R034")
        insertLogical($programcode)

end