package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "s2_r055"
    dialect "mvel"
    
    when 
        Person(age >= 18)
        Household(cashOnHand <= 256245)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 179355))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 205095))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 230670))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 256245))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 276705))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 297165))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 317790))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 338250))
            )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R055")
        insertLogical($programcode)

end
