package accessnyc.rules;
import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

// FairFares Rule
rule "s2_r034"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        Person( age >= 18, age <= 64)
        ( 
          (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 22692.5)) or 
          (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 30667.5)) or
          (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 38642.5)) or 
          (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 46617.5)) or 
          (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 54592.5)) or 
          (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 62567.5)) or 
          (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 70542.5)) or
          (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 78517.5))
        
        ) 
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R034")
        insertLogical($programcode)

end