package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household

import accessnyc.rules.income.IncomeHouseholdTotalYearly
import accessnyc.rules.income.IncomeHouseholdHasCashAssistance
import accessnyc.rules.income.IncomeHouseholdHasSSI
import accessnyc.rules.household.FosterChildren

rule "s2_r008 by income"
    dialect "mvel"
    
    when 
        Person( age <= 5 )
        
        (
               (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 15960))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 21640))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 27320))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 33000))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 38680))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 44360))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 50040))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 55720))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R008")
        insertLogical($programcode)

end

rule "s2_r008 Cash Assistance/SSI"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        (IncomeHouseholdHasCashAssistance(value == true) or IncomeHouseholdHasSSI(value == true))

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R008")
        insertLogical($programcode)

end

rule "s2_r008 has foster child"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        FosterChildren(value > 0)

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R008")
        insertLogical($programcode)

end