package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalMonthly

rule "S2R027"
    dialect "mvel"
    
    when 
        //This is a person 60 or over.
        Person( age >= 60 )
        and (
               (Household(members == 1) and IncomeHouseholdTotalMonthly(amount <= 1287))
            or (Household(members == 2) and IncomeHouseholdTotalMonthly(amount <= 1736))
            or (Household(members == 3) and IncomeHouseholdTotalMonthly(amount <= 2184))
            or (Household(members == 4) and IncomeHouseholdTotalMonthly(amount <= 2633))
            or (Household(members == 5) and IncomeHouseholdTotalMonthly(amount <= 3081))
            or (Household(members == 6) and IncomeHouseholdTotalMonthly(amount <= 3530))
            or (Household(members == 7) and IncomeHouseholdTotalMonthly(amount <= 3980))
            or (Household(members == 8) and IncomeHouseholdTotalMonthly(amount <= 4430))
            )
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R027")
        insertLogical($programcode)
        System.out.println("Rule S2R027 fired")

end