package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "s2_r058"
    dialect "mvel"
    
    when 
        Person(age >= 19, age <= 64, benefitsMedicaid == false, benefitsMedicaidDisability == false)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 31920))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 43280))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 54640))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 66000))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 77360))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 88720))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 100080))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 111440))
            )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R058")
        insertLogical($programcode)

end
