package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeMedicaidTotalYearly
import accessnyc.rules.household.MembersMedicaid

rule "s2_r038 1-2"
    dialect "mvel"
    
    when 
        Person( headOfHousehold == true, pregnant == true ) or Person( headOfHouseholdRelation == "Spouse", pregnant == true )
        (
           (MembersMedicaid(value == 1) and IncomeMedicaidTotalYearly(amount <= 35591))
        or (MembersMedicaid(value == 2) and IncomeMedicaidTotalYearly(amount <= 48258))
        or (MembersMedicaid(value == 3) and IncomeMedicaidTotalYearly(amount <= 60924))
        or (MembersMedicaid(value == 4) and IncomeMedicaidTotalYearly(amount <= 73590))
        or (MembersMedicaid(value == 5) and IncomeMedicaidTotalYearly(amount <= 86257))
        or (MembersMedicaid(value == 6) and IncomeMedicaidTotalYearly(amount <= 98923))
        or (MembersMedicaid(value == 7) and IncomeMedicaidTotalYearly(amount <= 111590))
        or (MembersMedicaid(value == 8) and IncomeMedicaidTotalYearly(amount <= 124256))
        or (MembersMedicaid(value >= 9) and IncomeMedicaidTotalYearly(amount <= 136922))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R038")
        insertLogical($programcode)

end

rule "s2_r038 3"
    dialect "mvel"
    
    when 
        Person( age < 1 )
        (
           (MembersMedicaid(value == 1) and IncomeMedicaidTotalYearly(amount <= 35591))
        or (MembersMedicaid(value == 2) and IncomeMedicaidTotalYearly(amount <= 48258))
        or (MembersMedicaid(value == 3) and IncomeMedicaidTotalYearly(amount <= 60924))
        or (MembersMedicaid(value == 4) and IncomeMedicaidTotalYearly(amount <= 73590))
        or (MembersMedicaid(value == 5) and IncomeMedicaidTotalYearly(amount <= 86257))
        or (MembersMedicaid(value == 6) and IncomeMedicaidTotalYearly(amount <= 98923))
        or (MembersMedicaid(value == 7) and IncomeMedicaidTotalYearly(amount <= 111590))
        or (MembersMedicaid(value == 8) and IncomeMedicaidTotalYearly(amount <= 124256))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R038")
        insertLogical($programcode)

end

rule "s2_r038 4"
    dialect "mvel"
    
    when 
        Person( ( (age == 19 || age == 20) && headOfHouseholdRelation in ("Child", "FosterChild", "StepChild", "Grandchild", "SisterBrother", "StepSisterStepBrother") ) )
        (
           (MembersMedicaid(value == 1) and IncomeMedicaidTotalYearly(amount <= 24738))
        or (MembersMedicaid(value == 2) and IncomeMedicaidTotalYearly(amount <= 33542))
        or (MembersMedicaid(value == 3) and IncomeMedicaidTotalYearly(amount <= 42346))
        or (MembersMedicaid(value == 4) and IncomeMedicaidTotalYearly(amount <= 51150))
        or (MembersMedicaid(value == 5) and IncomeMedicaidTotalYearly(amount <= 59954))
        or (MembersMedicaid(value == 6) and IncomeMedicaidTotalYearly(amount <= 68758))
        or (MembersMedicaid(value == 7) and IncomeMedicaidTotalYearly(amount <= 77562))
        or (MembersMedicaid(value == 8) and IncomeMedicaidTotalYearly(amount <= 86366))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R038")
        insertLogical($programcode)

end

rule "s2_r038 5"
    dialect "mvel"
    
    when 
        Person( age <= 18 && headOfHousehold == true ) or Person( age <= 18 && headOfHouseholdRelation in ("Spouse", "Child", "FosterChild", "StepChild", "Grandchild", "SisterBrother", "StepSisterStepBrother"))
        (
           (MembersMedicaid(value == 1) and IncomeMedicaidTotalYearly(amount <= 24579))
        or (MembersMedicaid(value == 2) and IncomeMedicaidTotalYearly(amount <= 33326))
        or (MembersMedicaid(value == 3) and IncomeMedicaidTotalYearly(amount <= 42073))
        or (MembersMedicaid(value == 4) and IncomeMedicaidTotalYearly(amount <= 50820))
        or (MembersMedicaid(value == 5) and IncomeMedicaidTotalYearly(amount <= 59568))
        or (MembersMedicaid(value == 6) and IncomeMedicaidTotalYearly(amount <= 68315))
        or (MembersMedicaid(value == 7) and IncomeMedicaidTotalYearly(amount <= 77062))
        or (MembersMedicaid(value == 8) and IncomeMedicaidTotalYearly(amount <= 85809))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R038")
        insertLogical($programcode)

end

rule "s2_r038 6"
    dialect "mvel"
    
    when 
        (
           (MembersMedicaid(value == 1) and IncomeMedicaidTotalYearly(amount <= 22025))
        or (MembersMedicaid(value == 2) and IncomeMedicaidTotalYearly(amount <= 29864))
        or (MembersMedicaid(value == 3) and IncomeMedicaidTotalYearly(amount <= 37702))
        or (MembersMedicaid(value == 4) and IncomeMedicaidTotalYearly(amount <= 45540))
        or (MembersMedicaid(value == 5) and IncomeMedicaidTotalYearly(amount <= 53379))
        or (MembersMedicaid(value == 6) and IncomeMedicaidTotalYearly(amount <= 61217))
        or (MembersMedicaid(value == 7) and IncomeMedicaidTotalYearly(amount <= 69056))
        or (MembersMedicaid(value == 8) and IncomeMedicaidTotalYearly(amount <= 76894))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R038")
        insertLogical($programcode)

end