package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "s2_r060"
    dialect "mvel"
    
    when 
        Person(benefitsMedicaid == true) or Person(benefitsMedicaidDisability == true)

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R060")
        insertLogical($programcode)

end