package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "s2_r018"
    dialect "mvel"
    
    when 
        Household(city == "NYC", livingOwner == true)
        Person(veteran == true, livingOwnerOnDeed == true)
    
        

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R018")
        insertLogical($programcode)
        System.out.println("Rule s2_r018")

end