package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household

import accessnyc.rules.income.IncomeHouseholdTotalYearlyLessGifts

rule "s2_r015"
    dialect "mvel"
    
    when
        
        Household(city == "NYC", livingRenting == true, livingRentalType in ("RentControlled", "HDFC", "RentRegulatedHotel", "MitchellLama","Section213")) 
        Person(headOfHousehold == true, livingRentalOnLease == true, age >= 62)  
        IncomeHouseholdTotalYearlyLessGifts ( amount <= 50000) 


    then
    
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R015")
        insertLogical($programcode)
end
