package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly
import accessnyc.rules.household.MembersPlusPregnant

rule "S2R029 pregnant, medicaid or disability medicaid"
    dialect "mvel"
    
    when 
        (Person( pregnant == true ))
        (Person(benefitsMedicaid == true) or Person(benefitsMedicaidDisability == true))
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R029")
        insertLogical($programcode)


end

rule "S2R029 income limits with pregnant household member"
    dialect "mvel"
    
    when 
        (Person( pregnant == true ))
        and (
               (MembersPlusPregnant(value == 1) and IncomeHouseholdTotalYearly(amount <= 35591))
            or (MembersPlusPregnant(value == 2) and IncomeHouseholdTotalYearly(amount <= 48258))
            or (MembersPlusPregnant(value == 3) and IncomeHouseholdTotalYearly(amount <= 60924))
            or (MembersPlusPregnant(value == 4) and IncomeHouseholdTotalYearly(amount <= 73590))
            or (MembersPlusPregnant(value == 5) and IncomeHouseholdTotalYearly(amount <= 86257))
            or (MembersPlusPregnant(value == 6) and IncomeHouseholdTotalYearly(amount <= 98923))
            or (MembersPlusPregnant(value == 7) and IncomeHouseholdTotalYearly(amount <= 111590))
            or (MembersPlusPregnant(value == 8) and IncomeHouseholdTotalYearly(amount <= 124256))
            or (MembersPlusPregnant(value == 9) and IncomeHouseholdTotalYearly(amount <= 136923))
            )
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R029")
        insertLogical($programcode)


end
