package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly


rule "s2_r013 "
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        Person(headOfHousehold == true, age >= 18)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly( amount <= 54350 )) 
            or (Household(members == 2) and IncomeHouseholdTotalYearly( amount <= 62150 )) 
            or (Household(members == 3) and IncomeHouseholdTotalYearly( amount <= 69900 ))
            or (Household(members == 4) and IncomeHouseholdTotalYearly( amount <= 77650 ))
            or (Household(members == 5) and IncomeHouseholdTotalYearly( amount <= 83850 ))
            or (Household(members == 6) and IncomeHouseholdTotalYearly( amount <= 90050 ))
            or (Household(members == 7) and IncomeHouseholdTotalYearly( amount <= 96300 ))
            or (Household(members == 8) and IncomeHouseholdTotalYearly( amount <= 102500 ))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R013")
        insertLogical($programcode)

end