package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly


rule "s2_r013 "
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        Person(headOfHousehold == true, age >= 18)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly( amount <= 56700 )) 
            or (Household(members == 2) and IncomeHouseholdTotalYearly( amount <= 64800 )) 
            or (Household(members == 3) and IncomeHouseholdTotalYearly( amount <= 72900 ))
            or (Household(members == 4) and IncomeHouseholdTotalYearly( amount <= 81000 ))
            or (Household(members == 5) and IncomeHouseholdTotalYearly( amount <= 87500 ))
            or (Household(members == 6) and IncomeHouseholdTotalYearly( amount <= 94000 ))
            or (Household(members == 7) and IncomeHouseholdTotalYearly( amount <= 100450 ))
            or (Household(members == 8) and IncomeHouseholdTotalYearly( amount <= 106950 ))
        )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R013")
        insertLogical($programcode)

end