package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

rule "S2R027"
    dialect "mvel"
    
    when 
        Household(city == "NYC") 
        Person( age >= 60 )
        and (
               (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 23940))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 32460))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 40980))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 49500))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 58020))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 66540))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 75060))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 83580))
            )
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R027")
        insertLogical($programcode)

end