package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeOwnersTotalYearly

rule "s2_r012 STAR"
    dialect "mvel"
    
    when 
        Household(city == "NYC", livingOwner == true)
        IncomeOwnersTotalYearly( amount <= 500000 )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R012")
        insertLogical($programcode)

end
