package accessnyc.rules;

import accessnyc.response.EligibleProgram
import accessnyc.rules.income.IncomeAdultsChildrenTotalMonthly
import accessnyc.rules.income.IncomePersonMonthly 
import accessnyc.rules.income.IncomePersonItemMonthly 
import accessnyc.request.Household
import accessnyc.request.Person


rule "s2_r003.5"
    dialect "mvel"
    when 
        Household(city == "NYC") 
        Person( age <= 5) 

        ( 
          (Household(members == 2)  and IncomeAdultsChildrenTotalMonthly(amount <= 6156)) or
          (Household(members == 3)  and IncomeAdultsChildrenTotalMonthly(amount <= 7604)) or 
          (Household(members == 4)  and IncomeAdultsChildrenTotalMonthly(amount <= 9053)) or 
          (Household(members == 5)  and IncomeAdultsChildrenTotalMonthly(amount <= 10501)) or 
          (Household(members == 6)  and IncomeAdultsChildrenTotalMonthly(amount <= 11949)) or 
          (Household(members == 7)  and IncomeAdultsChildrenTotalMonthly(amount <= 12221)) or
          (Household(members == 8)  and IncomeAdultsChildrenTotalMonthly(amount <= 12493))
        ) 
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R003")
        insertLogical($programcode)

end
