package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "S2R030"
    dialect "mvel"
    
    when 
        Household( city == "NYC")
        Person( age >= 13, age <= 21 )
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R030")
        insertLogical($programcode)
        System.out.println("Rule S2R030 fired")

end
