package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household


rule "s2_r057 age under 1"
    dialect "mvel"
    
    when 
        Person(age < 1)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly(amount > 35591))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount > 48258))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount > 60924))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount > 73590))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount > 86257))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount > 98923))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount > 111590))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount > 124256))
            )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R057")
        insertLogical($programcode)

end

rule "s2_r057 age 1-18"
    dialect "mvel"
    
    when 
        Person(age >= 1, age <= 18)
        not Person(age < 1)
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly(amount > 24579))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount > 33326))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount > 42073))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount > 50820))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount > 59568))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount > 68315))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount > 77062))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount > 85809))
            )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R057")
        insertLogical($programcode)

end
