package accessnyc.rules;

import accessnyc.response.EligibleProgram
import accessnyc.request.Person
import accessnyc.rules.expense.RequestExpense

rule "s2_r001: This is the last mile of rule s2r001"
    dialect "mvel"
    
    when 
        ( Person( age < 13 ) or Person( disabled == true ) or Person( blind == true ) )
        RequestExpense( amount > 0, type in ("ChildCare","DependentCare") )
        IncomeHeadAndSpouseEarnedYearly( amount > 0 )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R001")
        insertLogical($programcode)
end

