package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalMonthly

rule "S2R029"
    dialect "mvel"
    
    when 
        Household( city == "NYC")
        Person( pregnant == true )
        and (
               (Household(members == 1) and IncomeHouseholdTotalMonthly(amount <= 2960))
            or (Household(members == 2) and IncomeHouseholdTotalMonthly(amount <= 3733))
            or (Household(members == 3) and IncomeHouseholdTotalMonthly(amount <= 4606))
            or (Household(members == 4) and IncomeHouseholdTotalMonthly(amount <= 5280))
            or (Household(members == 5) and IncomeHouseholdTotalMonthly(amount <= 6053))
            or (Household(members == 6) and IncomeHouseholdTotalMonthly(amount <= 6826))
            or (Household(members == 7) and IncomeHouseholdTotalMonthly(amount <= 7599))
            )
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R029")
        insertLogical($programcode)
        System.out.println("Rule S2R029 fired")

end