package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

rule "s2_r025"
    dialect "mvel"
    
    when 
        Person( age >= 55, unemployed == true )
        
        (
               (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 19563))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 26438))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 33313))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 40188))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 47063))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 53938))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 60813))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 67688))
        )
        
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R025")
        insertLogical($programcode)

end


