package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalMonthly


rule "s2_r031"
    dialect "mvel"
    
    when 

        Household( city == "NYC" )
        Person( benefitsMedicaid == false, benefitsMedicaidDisability == false) 
        (
           (Household(members == 1) and IncomeHouseholdTotalMonthly(amount <= 2909))
        or (Household(members == 2) and IncomeHouseholdTotalMonthly(amount <= 3931))
        or (Household(members == 3) and IncomeHouseholdTotalMonthly(amount <= 4953))
        or (Household(members == 4) and IncomeHouseholdTotalMonthly(amount <= 5975))
        or (Household(members == 5) and IncomeHouseholdTotalMonthly(amount <= 6997))
        or (Household(members == 6) and IncomeHouseholdTotalMonthly(amount <= 8019))
        or (Household(members == 7) and IncomeHouseholdTotalMonthly(amount <= 9041))
        or (Household(members == 8) and IncomeHouseholdTotalMonthly(amount <= 10063))
        )
    
    then

        $programcode = new EligibleProgram()
        $programcode.setCode("S2R031")
        insertLogical($programcode)

end