package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

rule "s2_r022.2"
    dialect "mvel"
    
    when 
        Household(city == "NYC") 
        (Person(pregnant == true) or Person(age < 6))
        (
            (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 26973))
            or (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 36482))
            or (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 45991))
            or (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 55500))
            or (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 65009))
            or (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 74518))
            or (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 84027))
            or (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 93536))
            )
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R022")
        insertLogical($programcode)

end