package accessnyc.rules;

import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHeadAndSpouseEarnedYearly
import accessnyc.rules.household.HeadOfHouseholdMarried


rule "s2_r037 head of household"
    dialect "mvel"
    
    when 

        Person( headOfHousehold == true && disabled == true) or Person( headOfHousehold == true && blind == true ) or Person( headOfHousehold == true && age >= 65 )
        (
            (HeadOfHouseholdMarried(value == false) and IncomeHeadAndSpouseEarnedYearly(amount <= 20783) and Household( cashOnHand <= 31175))
            or (HeadOfHouseholdMarried(value == true) and IncomeHeadAndSpouseEarnedYearly(amount <= 28208) and Household( cashOnHand <= 42312))
        )
       
    then

        $programcode = new EligibleProgram()
        $programcode.setCode("S2R037")
        insertLogical($programcode)

end

rule "s2_r037 spouse"
    dialect "mvel"
    
    when 

        Person( headOfHouseholdRelation == "Spouse" && disabled == true ) or Person( headOfHouseholdRelation == "Spouse" && blind == true ) or Person( headOfHouseholdRelation == "Spouse" && age >= 65 )
        IncomeHeadAndSpouseEarnedYearly( amount <= 28208 ) 
        Household( cashOnHand <= 42312 )
       
    then

        $programcode = new EligibleProgram()
        $programcode.setCode("S2R037")
        insertLogical($programcode)

end

rule "s2_r037 not head or spouse"
    dialect "mvel"
    
    when 
        // interpret this person as a 1-person household
        IncomePersonEarnedYearly( person.blind == true, amount <= 20783 ) or IncomePersonEarnedYearly( person.disabled == true, amount <= 20783 ) or IncomePersonEarnedYearly( person.age >= 65, amount <= 20783 )
        Household( cashOnHand <= 31175 )
       
    then

        $programcode = new EligibleProgram()
        $programcode.setCode("S2R037")
        insertLogical($programcode)

end