package accessnyc.rules;
import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeAdultsTotalMonthly
import accessnyc.rules.expense.ExpenseHouseholdHasHeating


rule "s2_r019"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        not (Household(livingRentalType == "NYCHA") and not (ExpenseHouseholdHasHeating(value == true))) // need to check this logic is working
        not Household(livingHotel == true)
        (
               (Household(members == 1) and IncomeAdultsTotalMonthly(amount <= 2318))
            or (Household(members == 2) and IncomeAdultsTotalMonthly(amount <= 3031))
            or (Household(members == 3) and IncomeAdultsTotalMonthly(amount <= 3744))
            or (Household(members == 4) and IncomeAdultsTotalMonthly(amount <= 4457))
            or (Household(members == 5) and IncomeAdultsTotalMonthly(amount <= 5170))
            or (Household(members == 6) and IncomeAdultsTotalMonthly(amount <= 5883))
            or (Household(members == 7) and IncomeAdultsTotalMonthly(amount <= 6017))
            or (Household(members == 8) and IncomeAdultsTotalMonthly(amount <= 6150))
            or (Household(members == 9) and IncomeAdultsTotalMonthly(amount <= 6284))
            or (Household(members == 10) and IncomeAdultsTotalMonthly(amount <= 6418))
            or (Household(members == 11) and IncomeAdultsTotalMonthly(amount <= 6733))
            
            )

    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R019")
        insertLogical($programcode)

end