package accessnyc.rules;
import accessnyc.response.EligibleProgram

import accessnyc.request.Person
import accessnyc.request.Household
import accessnyc.rules.income.IncomeHouseholdTotalYearly

// FairFares Rule
rule "s2_r034"
    dialect "mvel"
    
    when 
        Household(city == "NYC")
        Person( age >= 18, age <= 64)
        ( 
          (Household(members == 1) and IncomeHouseholdTotalYearly(amount <= 21837)) or 
          (Household(members == 2) and IncomeHouseholdTotalYearly(amount <= 29638)) or
          (Household(members == 3) and IncomeHouseholdTotalYearly(amount <= 37439)) or 
          (Household(members == 4) and IncomeHouseholdTotalYearly(amount <= 45240)) or 
          (Household(members == 5) and IncomeHouseholdTotalYearly(amount <= 53041)) or 
          (Household(members == 6) and IncomeHouseholdTotalYearly(amount <= 60842)) or 
          (Household(members == 7) and IncomeHouseholdTotalYearly(amount <= 68643)) or
          (Household(members == 8) and IncomeHouseholdTotalYearly(amount <= 76444))
        
        ) 
    then
        $programcode = new EligibleProgram()
        $programcode.setCode("S2R034")
        insertLogical($programcode)

end