package accessnyc.rules.snap;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IncomePersonHasSSIorCashAssistance implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private accessnyc.request.Person person;
   private java.lang.Boolean value;

   public IncomePersonHasSSIorCashAssistance()
   {
   }

   public accessnyc.request.Person getPerson()
   {
      return this.person;
   }

   public void setPerson(accessnyc.request.Person person)
   {
      this.person = person;
   }

   public java.lang.Boolean getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Boolean value)
   {
      this.value = value;
   }

   public IncomePersonHasSSIorCashAssistance(accessnyc.request.Person person,
         java.lang.Boolean value)
   {
      this.person = person;
      this.value = value;
   }

}