package accessnyc.rules.snap;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IncomeHouseholdAllSSIOrCash implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean value;

   public IncomeHouseholdAllSSIOrCash()
   {
   }

   public java.lang.Boolean getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Boolean value)
   {
      this.value = value;
   }

   public IncomeHouseholdAllSSIOrCash(java.lang.Boolean value)
   {
      this.value = value;
   }

}