package accessnyc.rules.snap;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IncomeDifMembersMinusSSI implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer value;

   public IncomeDifMembersMinusSSI()
   {
   }

   public java.lang.Integer getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Integer value)
   {
      this.value = value;
   }

   public IncomeDifMembersMinusSSI(java.lang.Integer value)
   {
      this.value = value;
   }

}