package accessnyc.rules.scrie;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SCRIERentIncomeRatioMonthly implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Float value;

   public SCRIERentIncomeRatioMonthly()
   {
   }

   public java.lang.Float getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Float value)
   {
      this.value = value;
   }

   public SCRIERentIncomeRatioMonthly(java.lang.Float value)
   {
      this.value = value;
   }

}