package accessnyc.rules.household;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BlindDisabledHousehold implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean value;

   public BlindDisabledHousehold()
   {
   }

   public java.lang.Boolean getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Boolean value)
   {
      this.value = value;
   }

   public BlindDisabledHousehold(java.lang.Boolean value)
   {
      this.value = value;
   }

}