package accessnyc.rules.household;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ChildrenStudentEITCDefinition implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer value;

   public ChildrenStudentEITCDefinition()
   {
   }

   public java.lang.Integer getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Integer value)
   {
      this.value = value;
   }

   public ChildrenStudentEITCDefinition(java.lang.Integer value)
   {
      this.value = value;
   }

}