package accessnyc.rules.household;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MembersNuclearOnly implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer value;

   public MembersNuclearOnly()
   {
   }

   public java.lang.Integer getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Integer value)
   {
      this.value = value;
   }

   public MembersNuclearOnly(java.lang.Integer value)
   {
      this.value = value;
   }

}