package accessnyc.rules.valid;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidPerson implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Person")
   private accessnyc.request.Person person;

   public ValidPerson()
   {
   }

   public accessnyc.request.Person getPerson()
   {
      return this.person;
   }

   public void setPerson(accessnyc.request.Person person)
   {
      this.person = person;
   }

   public ValidPerson(accessnyc.request.Person person)
   {
      this.person = person;
   }

}