package accessnyc.rules.income;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IncomeHouseholdTotalYearly implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Float amount;

   public IncomeHouseholdTotalYearly()
   {
   }

   public java.lang.Float getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Float amount)
   {
      this.amount = amount;
   }

   public IncomeHouseholdTotalYearly(java.lang.Float amount)
   {
      this.amount = amount;
   }

}