package accessnyc.rules.income;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IncomePersonHasDM implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean value;

   public IncomePersonHasDM()
   {
   }

   public java.lang.Boolean getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.Boolean value)
   {
      this.value = value;
   }

   public IncomePersonHasDM(java.lang.Boolean value)
   {
      this.value = value;
   }

}